---

- hosts: localhost
  remote_user: root
  vars:
   splunk: 101
   velo: 102
  tasks:
    - name: Execute ip a
      become_user: root
      become: true
      ansible.builtin.command: qm guest exec {{ splunk }} -- /bin/sh -c "ip a show dev eth0"
      register: ip_output
    - name: Get IP
      set_fact:
        splunk_ip: "{{ ip_output | regex_search('inet (\\d*\\.\\d*\\.\\d*\\.\\d*)/', '\\1') | first }}"

    - name: "Add Splunk"
      add_host:
        name: splunk
        ansible_host: '{{ splunk_ip }}'
        ansible_connection: ssh
        ansible_ssh_host: '{{ splunk_ip }}'
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

- name: "Velo"
  hosts: splunk
  become: true
  tasks: 
    - name: Download Splunk cant use get_url due to bug
      ansible.builtin.shell: wget -O /tmp/splunk-9.3.1-0b8d769cb912-linux-2.6-amd64.deb "https://download.splunk.com/products/splunk/releases/9.3.1/linux/splunk-9.3.1-0b8d769cb912-linux-2.6-amd64.deb"
    - name: install Splunk
      apt:
        deb: /tmp/splunk-9.3.1-0b8d769cb912-linux-2.6-amd64.deb
