---

- hosts: localhost
  remote_user: root
  vars:
   splunk: 101
   velo: 102
  tasks:
    - name: Execute ip a
      become_user: root
      become: true
      ansible.builtin.command: qm guest exec {{ splunk }} -- /bin/sh -c "ip a show dev eth0"
      register: ip_output
    - name: Get IP
      set_fact:
        splunk_ip: "{{ ip_output | regex_search('inet (\\d*\\.\\d*\\.\\d*\\.\\d*)/', '\\1') | first }}"

    - name: "Add Splunk"
      add_host:
        name: splunk
        ansible_host: '{{ splunk_ip }}'
        ansible_connection: ssh
        ansible_ssh_host: '{{ splunk_ip }}'
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

    - name: Execute ip a
      become_user: root
      become: true
      ansible.builtin.command: qm guest exec {{ velo }} -- /bin/sh -c "ip a show dev eth0"
      register: ip_output
    - name: Get IP
      set_fact:
        velo_ip: "{{ ip_output | regex_search('inet (\\d*\\.\\d*\\.\\d*\\.\\d*)/', '\\1') | first }}"

    - name: "Add Velo"
      add_host:
        name: velo
        ansible_host: '{{ velo_ip }}'
        ansible_connection: ssh
        ansible_ssh_host: '{{ velo_ip }}'
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"


- name: "Splunk"
  hosts: splunk
  become: true
  vars:
   splunk_exec : /opt/splunk/bin/splunk
   splunk_service: Splunkd
  tasks: 
    - name: Install dependencies
      package:
        name:
          - sysfsutils
        state: present
    - name: Download Splunk cant use get_url due to bug
      ansible.builtin.shell: wget -O /tmp/splunk-9.3.1-0b8d769cb912-linux-2.6-amd64.deb "https://download.splunk.com/products/splunk/releases/9.3.1/linux/splunk-9.3.1-0b8d769cb912-linux-2.6-amd64.deb"
      args: 
        creates: /tmp/splunk-9.3.1-0b8d769cb912-linux-2.6-amd64.deb
    - name: install Splunk
      apt:
        deb: /tmp/splunk-9.3.1-0b8d769cb912-linux-2.6-amd64.deb
    - name: Disable transparent huge pages for performance
      lineinfile:
        path: /etc/sysfs.conf
        line: |
          kernel/mm/transparent_hugepage/enabled = never
    - name: Update System Packages
      apt:
        update_cache: yes
        upgrade: dist
    - name: Upload Splunk user seed file
      ansible.builtin.shell: wget -O /opt/splunk/etc/system/local/user-seed.conf "https://raw.githubusercontent.com/onchaosteam/FAK/refs/heads/main/user-seed.conf"
    - name: Setup Splunk
      shell: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
    - name: Stop Splunk
      shell: /opt/splunk/bin/splunk stop     
    - name: Create Splunk Service
      shell: /opt/splunk/bin/splunk enable boot-start -user splunk -systemd-managed 1    
    - name: Recursively change ownership of a directory
      file:
        path: /opt/splunk
        state: directory
        recurse: yes
        owner: splunk
        group: splunk
    - name: Update the systemd file for Splunk
      ini_file:
        path: "/etc/systemd/system/{{ splunk_service }}.service"
        section: Service
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: 0644
      loop:
        - { option: "LimitNOFILE", value: "1024000" }
        - { option: "LimitNPROC", value: "512000" }
        - { option: "LimitFSIZE", value: "infinity" }
        - { option: "LimitDATA", value: "infinity" }
        - { option: "LimitCORE", value: "infinity" }
        - { option: "TasksMax", value: "infinity" }
        - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Start Splunk and enable for boot
      service:
        name: Splunkd
        state: started
        enabled: yes
